version: '3'
services:

  postgres:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: admin
      POSTGRES_DB: fortuhost
    volumes:
      - db_data:/var/lib/postgresql/fortuhost
    ports:
      - "5435:5432"

  redis:
    image: redis:7.0.11-alpine
    ports:
      - "16379:6379"


volumes:
  db_data: