# Generated by Django 4.2.2 on 2023-06-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostedApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('docker_container_id', models.CharField(blank=True, max_length=100, verbose_name='ID контейнера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('started_at', models.DateTimeField(auto_now=True, verbose_name='Время запуска')),
                ('status', models.CharField(choices=[('RUN', 'Run'), ('STOP', 'Stop'), ('DELETE', 'Delete'), ('RESTART', 'Restart')], default='STOP', max_length=20, verbose_name='Статус приложения')),
            ],
            options={
                'verbose_name': 'Приложение',
                'verbose_name_plural': 'Приложения',
            },
        ),
    ]
